# Generated by Django 5.0.14 on 2026-02-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('professor', 'Professor'), ('admin', 'Admin')], default='student', max_length=20),
        ),
    ]
