# Generated by Django 5.0.14 on 2026-03-01 16:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_sso_provider_userprofile_student_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='allow_public_university_info',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='university',
            name='branding_primary_color',
            field=models.CharField(default='#2563eb', max_length=20),
        ),
        migrations.AddField(
            model_name='university',
            name='branding_secondary_color',
            field=models.CharField(default='#14b8a6', max_length=20),
        ),
        migrations.AddField(
            model_name='university',
            name='custom_domain',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='university',
            name='db_alias',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='university',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='university',
            name='logo_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='university',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='university',
            name='subdomain',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('event_type', models.CharField(choices=[('auth', 'Auth'), ('data_access', 'Data Access'), ('data_change', 'Data Change'), ('integration', 'Integration'), ('security', 'Security'), ('system', 'System')], default='system', max_length=30)),
                ('action', models.CharField(max_length=120)),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=255)),
                ('status_code', models.IntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('duration_ms', models.IntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.university')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='UniversityIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('widget', 'Website Widget'), ('lms', 'LMS'), ('erp', 'ERP'), ('calendar', 'Calendar'), ('sso', 'SSO'), ('api', 'API Integration')], max_length=20)),
                ('provider_name', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('scaffold', 'Scaffold'), ('active', 'Active'), ('disabled', 'Disabled')], default='scaffold', max_length=20)),
                ('base_url', models.URLField(blank=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('api_key_hash', models.CharField(blank=True, max_length=128)),
                ('api_key_last4', models.CharField(blank=True, max_length=4)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='accounts.university')),
            ],
            options={
                'ordering': ('category', 'provider_name'),
                'unique_together': {('university', 'category', 'provider_name')},
            },
        ),
    ]
