# Generated by Django 5.0.14 on 2026-03-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airequest',
            name='request_type',
            field=models.CharField(choices=[('flashcard', 'Flashcard Generation'), ('quiz', 'Quiz Generation'), ('summary', 'Summary Generation'), ('fact', 'Fact Extraction'), ('exam_prep', 'Exam Prep Slides'), ('ask', 'RAG Question Answering')], max_length=20),
        ),
    ]
